title = 'Frequency Table of Tree Distance'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/292"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small_random.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 2

[[tests]]
    name = "uni.cpp"
    number = 1

[[tests]]
    name = "almost_uni.cpp"
    number = 2

[[tests]]
    name = "line.cpp"
    number = 1

[[solutions]]
    name = "naive.cpp"
    allow_tle = true

[params]
    N_MAX = 200_000
