title = 'Static Rectangle Add Rectangle Sum'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/771"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    wrong = true
    allow_tle = true


[params]
    N_MIN = 1
    N_MAX = 200_000
    Q_MIN = 1
    Q_MAX = 200_000
    X_MIN = 0
    X_MAX = 1_000_000_000
    Y_MIN = 0
    Y_MAX = 1_000_000_000
    MOD = 998_244_353
