title = 'Pow of Formal Power Series'
timelimit = 10
forum = "https://github.com/yosupo06/library-checker-problems/issues/386"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "lower_deg_zero.cpp"
    number = 8
[[tests]]
    name = "all_zero.cpp"
    number = 2
[[tests]]
    name = "monomial.cpp"
    number = 4
[[tests]]
    name = "monomial_ans_low_deg.cpp"
    number = 4
[[tests]]
    name = "lower_deg_zero2.cpp"
    number = 4
[[tests]]
    name = "binary_exp_max.cpp"
    number = 1
[[tests]]
    name = "overflow_killer.in"
    number = 2
[[tests]]
    name = "M_zero.cpp"
    number = 2
[[tests]]
    name = "hack.in"
    number = 1

[[solutions]]
    name = "wa_overflow.cpp"
    expect = "WA"
    
[params]
    N_MAX = 500000
    M_MAX = 1_000_000_000_000_000_000
    MOD = 998244353
