title = 'Consecutive Terms of Linear Recurrent Sequence'
timelimit = 10.0
forum = 'https://github.com/yosupo06/library-checker-problems/issues/1007'

[[tests]]
    name = "example.in"
    number = 3

[[tests]]
    name = "small.cpp"
    number = 10

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "near_65536.cpp"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 3

[[tests]]
    name = "trailing_zeros.cpp"
    number = 10

[[tests]]
    name = "zero.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    allow_re = true

[[solutions]]
    name = "correct_doubling.cpp"
    allow_tle = true

[params]
  D_MAX = 100_000
  M_MAX = 500_000
  K_MAX = 1_000_000_000_000_000_000
  MOD = 998_244_353
