title = 'Min Plus Convolution (Convex and Arbitrary)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/727"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 9

[[tests]]
    name = "med_random.cpp"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "monotone.cpp"
    number = 4

[[tests]]
    name = "small_slopes.cpp"
    number = 2

[[tests]]
    name = "near_power_of_2.cpp"
    number = 9

[[tests]]
    name = "hack.in"
    number = 1

[[tests]]
    name = "large_small.cpp"
    number = 4

[[tests]]
    name = "only_first_small.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    N_MAX = 524288
    A_MIN = 0
    A_MAX = 1000000000
