title = 'Point Add Range Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/20"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 10

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 5


[params]
    N_AND_Q_MAX = 500_000
    A_AND_X_MAX = 1_000_000_000
