title = 'Factorial'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/128"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 2
[[tests]]
    name = "near_max.cpp"
    number = 2
[[tests]]
    name = "near_half.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true


[params]
    T_MAX = 5
    MOD = 998244353
