[problems.aplusb]
    dir = 'sample/aplusb'

# Data Structure
[problems.unionfind]
    dir = 'datastructure/unionfind'

[problems.staticrmq]
    dir = 'datastructure/staticrmq'

[problems.point_add_range_sum]
    dir = 'datastructure/point_add_range_sum'

[problems.point_set_range_composite]
    dir = 'datastructure/point_set_range_composite'

[problems.range_affine_range_sum]
    dir = 'datastructure/range_affine_range_sum'

[problems.vertex_add_path_sum]
    dir = 'datastructure/vertex_add_path_sum'

[problems.vertex_add_subtree_sum]
    dir = 'datastructure/vertex_add_subtree_sum'

[problems.dynamic_tree_vertex_add_path_sum]
    dir = 'datastructure/dynamic_tree_vertex_add_path_sum'

[problems.dynamic_tree_vertex_add_subtree_sum]
    dir = 'datastructure/dynamic_tree_vertex_add_subtree_sum'

[problems.line_add_get_min]
    dir = 'datastructure/line_add_get_min'

[problems.segment_add_get_min]
    dir = 'datastructure/segment_add_get_min'

[problems.rectangle_sum]
    dir = 'datastructure/rectangle_sum'

[problems.queue_operate_all_composite]
    dir = 'datastructure/queue_operate_all_composite'

# Graph
[problems.lca]
    dir = 'graph/lca'

[problems.scc]
    dir = 'graph/scc'

[problems.bipartitematching]
    dir = 'graph/bipartitematching'

[problems.general_matching]
    dir = 'graph/general_matching'

[problems.assignment]
    dir = 'graph/assignment'

[problems.directedmst]
    dir = 'graph/directedmst'

[problems.manhattanmst]
    dir = 'graph/manhattanmst'

[problems.dominatortree]
    dir = 'graph/dominatortree'

[problems.maximum_independent_set]
    dir = 'graph/maximum_independent_set'

# String
[problems.zalgorithm]
    dir = 'string/zalgorithm'

[problems.suffixarray]
    dir = 'string/suffixarray'

[problems.number_of_substrings]
    dir = 'string/number_of_substrings'

[problems.runenumerate]
    dir = 'string/runenumerate'

# Math
[problems.factorize]
    dir = 'math/factorize'

[problems.sqrt_mod]
    dir = 'math/sqrt_mod'

[problems.tetration_mod]
    dir = 'math/tetration_mod'

[problems.montmort_number_mod]
    dir = 'math/montmort_number_mod'

[problems.kth_root_integer]
    dir = 'math/kth_root_integer'

[problems.discrete_logarithm_mod]
    dir = 'math/discrete_logarithm_mod'

[problems.matrix_det]
    dir = 'math/matrix_det'

[problems.sparse_matrix_det]
    dir = 'math/sparse_matrix_det'

[problems.system_of_linear_equations]
    dir = 'math/system_of_linear_equations'

[problems.convolution_mod]
    dir = 'math/convolution_mod'

[problems.multipoint_evaluation]
    dir = 'math/multipoint_evaluation'

[problems.polynomial_interpolation]
    dir = 'math/polynomial_interpolation'

[problems.partition_function]
    dir = 'math/partition_function'

[problems.bernoulli_number]
    dir = 'math/bernoulli_number'

[problems.sum_of_floor_of_linear]
    dir = 'math/sum_of_floor_of_linear'

[problems.inv_of_formal_power_series]
    dir = 'math/inv_of_formal_power_series'

[problems.exp_of_formal_power_series]
    dir = 'math/exp_of_formal_power_series'

[problems.log_of_formal_power_series]
    dir = 'math/log_of_formal_power_series'

[problems.sqrt_of_formal_power_series]
    dir = 'math/sqrt_of_formal_power_series'

[problems.two_sat]
    dir = 'math/two_sat'
