[problems.aplusb]
    title = 'A + B'
    dir = 'sample/aplusb'

# Data Structure
[problems.unionfind]
    title = 'Unionfind'
    dir = 'datastructure/unionfind'

[problems.staticrmq]
    title = 'Static RMQ'
    dir = 'datastructure/staticrmq'

# Graph
[problems.lca]
    title = 'Lowest Common Ancestor'
    dir = 'graph/lca'

[problems.scc]
    title = 'Strongly Connected Components'
    dir = 'graph/scc'

[problems.bipartitematching]
    title = 'Matching on Bipartite Graph'
    dir = 'graph/bipartitematching'

[problems.assignment]
    title = 'Assignment Problem'
    dir = 'graph/assignment'

[problems.directedmst]
    title = 'Directed MST'
    dir = 'graph/directedmst'

[problems.dominatortree]
    title = 'Dominator Tree'
    dir = 'graph/dominatortree'

# String
[problems.zalgorithm]
    title = 'Z Algorithm'
    dir = 'string/zalgorithm'

[problems.suffixarray]
    title = 'Suffix Array'
    dir = 'string/suffixarray'

[problems.runenumerate]
    title = 'Run Enumerate'
    dir = 'string/runenumerate'

# Math
[problems.factorize]
    title = 'Factorize'
    dir = 'math/factorize'

[problems.sqrt_mod]
    title = 'Sqrt Mod'
    dir = 'math/sqrt_mod'

[problems.matrix_det]
    title = 'Determinant of Matrix'
    dir = 'math/matrix_det'

[problems.sparse_matrix_det]
    title = 'Determinant of Sparse Matrix'
    dir = 'math/sparse_matrix_det'

[problems.convolution_mod]
    title = 'Convolution'
    dir = 'math/convolution_mod'

[problems.multipoint_evaluation]
    title = 'Multipoint Evaluation'
    dir = 'math/multipoint_evaluation'

[problems.polynomial_interpolation]
    title = 'Polynomial Interpolation'
    dir = 'math/polynomial_interpolation'

[problems.partition_function]
    title = 'K-th of Partition Function'
    dir = 'math/partition_function'

[problems.sum_of_floor_of_linear]
    title = 'Sum of Floor of Linear'
    dir = 'math/sum_of_floor_of_linear'

[problems.exp_of_formal_power_series]
    title = 'Exp of Formal Power Series'
    dir = 'math/exp_of_formal_power_series'

[problems.log_of_formal_power_series]
    title = 'Log of Formal Power Series'
    dir = 'math/log_of_formal_power_series'

[problems.two_sat]
    title = '2 Sat'
    dir = 'math/two_sat'
