title = 'Dynamic Sequence Range Affine Range Sum'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/242"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max.cpp"
    number = 5

[[tests]]
    name = "extreme_insertion.cpp"
    number = 3

[[tests]]
    name = "small.cpp"
    number = 10

[[tests]]
    name = "wrong_avl_killer.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    expect = "RE"

[params]
    N_AND_Q_MAX = 500_000
    MOD = 998244353
