title = 'Directed MST'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/39"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 5
