title = 'Polynomial Composite Set Power Series'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/944"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small_random.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "nm_01.cpp"
    number = 8

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    M_MAX = 100000
    N_MAX = 20
    MOD = 998244353
