title = 'Multivariate Convolution'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/633"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 2
[[tests]]
    name = "twos.cpp"
    number = 2
[[tests]]
    name = "threes.cpp"
    number = 2
[[tests]]
    name = "dim2.cpp"
    number = 2
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "k0.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    K_MAX = 18
    PROD_N_MAX = 262144
    MOD = 998244353
