title = 'Kth Root(Integer)'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/64"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 2
[[tests]]
    name = "all_k2.cpp"
    number = 2
[[tests]]
    name = "all_k3.cpp"
    number = 2
[[tests]]
    name = "near_border.cpp"
    number = 3
