title = 'Furthest Pair of Points'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/837"

[[tests]]
    name = "example.in"
    number = 1
    
[[tests]]
    name = "all_same.cpp"
    number = 1

[[tests]]
    name = "small_random.cpp"
    number = 8

[[tests]]
    name = "mid_random.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 8

[[tests]]
    name = "max_colinear.cpp"
    number = 2

[[tests]]
    name = "near_circle.cpp"
    number = 2

[[tests]]
    name = "near_grid.cpp"
    number = 2

[[tests]]
    name = "fix_near_grid.cpp"
    number = 2

[[tests]]
    name = "max_convex_hull.cpp"
    number = 1

[[tests]]
    name = "hack_uso_caliper.in"
    number = 1

[[tests]]
    name = "hack_uso_caliper_large.cpp"
    number = 15

[[solutions]]
    name = "uso_caliper.cpp"
    expect = "WA"

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    T_MAX = 100_000
    SUM_N_MAX = 500_000
    X_AND_Y_ABS_MAX = 1_000_000_000
