title = 'Counting Primes'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/388"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "max.cpp"
    number = 5
[[tests]]
    name = "small.cpp"
    number = 5
[[tests]]
    name = "very_small.cpp"
    number = 5
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "Grothendieck_prime.in"
    number = 1
[[tests]]
    name = "small_prime.in"
    number = 2
[[tests]]
    name = "boundaryA.cpp"
    number = 3
[[tests]]
    name = "boundaryB.cpp"
    number = 3

[params]
    N_MAX = 100_000_000_000
