title = 'Sqrt of Formal Power Series (Sparse)'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/767"

[[tests]]
    name = "example.in"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 10
[[tests]]
    name = "max_random.cpp"
    number = 10
[[tests]]
    name = "small_dense.cpp"
    number = 10
[[tests]]
    name = "small_N.cpp"
    number = 10
[[tests]]
    name = "min_K.cpp"
    number = 2


[[solutions]]
    name = "dense_correct.cpp"
    allow_tle = true

[params]
    N_MIN = 1
    N_MAX = 1_000_000
    K_MIN = 0
    K_MAX = 10
    MOD = 998_244_353
