version: 2

jobs:
  clang-compile:
    docker:
      - image: gcr.io/library-checker-project/library-checker-problem-env
    steps:
      - checkout
      - run:
          command: ./generate.py problems.toml --compileonly
          environment:
            CXX: clang++
            CXXFLAGS: -std=c++14 -stdlib=libc++ -Wall -Wextra
  generate:
    docker:
      - image: gcr.io/library-checker-project/library-checker-problem-env
    steps:
      - checkout
      - run: ulimit -s unlimited && ./generate.py problems.toml
      - persist_to_workspace:
          root: .
          paths:
            # sample/aplusb/
            - '*/*/in/*'
            - '*/*/out/*'
          
  genhtml:
    docker:
      - image: gcr.io/library-checker-project/library-checker-problem-env
    steps:
      - attach_workspace:
        at: .
      - checkout
      - run: ./deploy.py --htmldir /tmp/html --htmlonly
      - store_artifacts:
          path: /tmp/html

workflows:
  version: 2
  build:
    jobs:
      - clang-compile
      - generate
      - genhtml
          requires:
            - generate