version: 2.1

jobs:
  build:
    docker:
      - image: gcr.io/$PROJECT_ID/library-checker-problem-env
        auth:
          username: _json_key
          password: $GCR_KEY
    steps:
      - run: ls
      - run: ./generate.py problems.toml