title = 'Division of Hex Big Integers'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/1101"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 1
[[tests]]
    name = "medium.cpp"
    number = 3
[[tests]]
    name = "large.cpp"
    number = 2
[[tests]]
    name = "max.cpp"
    number = 3
[[tests]]
    name = "a_max_b_random.cpp"
    number = 3
[[tests]]
    name = "power.cpp"
    number = 1
[[tests]]
    name = "r_nearly_zero.cpp"
    number = 3
[[tests]]
    name = "length_ratio_integer.cpp"
    number = 6

[[solutions]]
    name = "correct.py"
    allow_tle = true

[params]
    T_MAX = 1600000
    LOG_16_A_AND_B_MAX = 1600000
    SUM_OF_CHARACTER_LENGTH = 3200002
