title = 'Rectangle Add Point Get'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/994"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 5
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "many_points.cpp"
    number = 1
[[tests]]
    name = "many_rectangles.cpp"
    number = 1
[[tests]]
    name = "small_coord.cpp"
    number = 3
[[tests]]
    name = "power_of_2.cpp"
    number = 2

[[solutions]]
    name = "naive_1.cpp"
    allow_re = true
[[solutions]]
    name = "naive_2.cpp"
    allow_re = true

[params]
    N_MAX = 100_000
    Q_MAX = 100_000
    COORD_MAX = 1000_000_000
    WEIGHT_MAX = 1000_000_000
