title = '$\sum_{i=0}^{\infty} r^i i^d$'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/99"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "0.cpp"
    number = 3
[[tests]]
    name = "2.cpp"
    number = 6

[[solutions]]
    name = "eulerian_table.cpp"
    expect = "RE"

[params]
    MOD = 998244353
    D_MIN = 0
    D_MAX = 10_000_000
