title = 'Dynamic Graph Vertex Add Component Sum'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/347"

[[tests]]
	name = "example.in"
	number = 1

[[tests]]
	name = "link_and_cut.cpp"
	number = 1

[[tests]]
	name = "small.cpp"
	number = 3

[[tests]]
	name = "random.cpp"
	number = 5

[[tests]]
	name = "max_random.cpp"
	number = 3

[[tests]]
	name = "dense.cpp"
	number = 3

[[solutions]]
	name = "naive.cpp"
	wrong = true

[params]
	N_AND_Q_MIN = 1
	N_AND_Q_MAX = 300_000
	N_AND_Q_SMALL_MAX = 1_000
	A_AND_X_MIN = 0
	A_AND_X_MAX = 1_000_000_000
