title = 'Hafnian of Matrix'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/467"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "large.cpp"
    number = 3
[[tests]]
    name = "max.cpp"
    number = 3
[[tests]]
    name = "hack77047.cpp"
    number = 1

[[solutions]]
    name = "naive.cpp"
    wrong = true
[[solutions]]
    name = "bitdp.cpp"
    wrong = true

[params]
    N_MIN = 2
    N_MAX = 38
    MOD = 998_244_353
