title = 'Static Range Count Distinct'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/770"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small_n.cpp"
    number = 3

[[tests]]
    name = "small_q.cpp"
    number = 1

[[tests]]
    name = "random.cpp"
    number = 6

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    N_MIN = 0
    N_MAX = 500_000
    Q_MIN = 0
    Q_MAX = 500_000
    A_MIN = 0
    A_MAX = 1_000_000_000
