title = 'Associative Array'
timelimit = 5.0
forum = 'https://github.com/yosupo06/library-checker-problems/issues/376'

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "unordered_map_killer.cpp"
    number = 3
[[tests]]
    name = "sparse_keys.cpp"
    number = 2
[[tests]]
    name = "2_powers.cpp"
    number = 1
[[tests]]
    name = "many_0set.cpp"
    number = 1
[[tests]]
    name = "many_0set_sparse.cpp"
    number = 1

[[tests]]
    name = "py_killer.cpp"
    number = 1
    
[[solutions]]
    name = "tle_unordered_map.cpp"
    allow_tle = true

[params]
    Q_MAX = 1_000_000
    K_AND_V_MAX = 1_000_000_000_000_000_000
