title = 'Enumerate Palindromes'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/574"

[[tests]]
    name = "example.in"
    number = 4

[[tests]]
    name = "small.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 5

[[tests]]
    name = "all_same.cpp"
    number = 5

[[solutions]]
    name ="naive.cpp"
    wrong = true

[params]
    N_MAX = 500000
