title = 'Cycle Detection (Directed)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/534"

[[tests]]
	name = "example.in"
	number = 3
[[tests]]
    name = "random.cpp"
    number = 10
[[tests]]
    name = "random_dense.cpp"
    number = 5
[[tests]]
    name = "random_dag.cpp"
    number = 10
[[tests]]
    name = "random_dag_dense.cpp"
    number = 5
[[tests]]
    name = "long_cycle.cpp"
    number = 2

[[solutions]]
	name = 'source_zero.cpp'
	expect = "TLE"

[params]
	N_MIN = 2
	N_MAX = 500000
	M_MIN = 1
	M_MAX = 500000

