title = 'System of Linear Equations'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/18"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "lowrank.cpp"
    number = 6
