title = 'Range Reverse Range Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/538"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small_random.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "nq_01.cpp"
    number = 8
[[tests]]
    name = "almost_t0.cpp"
    number = 1
[[tests]]
    name = "almost_t1.cpp"
    number = 1

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    N_MAX = 200_000
    Q_MAX = 200_000
    A_MAX = 1_000_000_000
