title = 'Determinant of Sparse Matrix'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/44"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "hack.in"
    number = 1
[[tests]]
    name = "hack2.cpp"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "perm_max_random.cpp"
    number = 5
[[tests]]
    name = "perm_plus_random.cpp"
    number = 5

[params]
    N_MAX = 3000
    M_MAX = 10000
    MOD = 998244353
