title = 'Tetration Mod'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/166"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "small.cpp"
    number = 1
[[tests]]
    name = "2_3_32.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max.cpp"
    number = 3
[[tests]]
    name = "max_998244353.cpp"
    number = 3
[[tests]]
    name = "max_1000000000.cpp"
    number = 3
