title = 'Dynamic Tree Subtree Add Subtree Sum'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/521"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "max_random.cpp"
    number = 5

[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_MAX = 200_000
    Q_MAX = 200_000
    VAL_MAX = 10_000_000
