title = 'Manhattan MST'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/180"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "many_cluster.cpp"
    number = 3
[[tests]]
    name = "enclosed.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    wrong = true