title = 'Kth Root(Mod)'
timelimit = 5
forum = "https://github.com/yosupo06/library-checker-problems/issues/21"

[[tests]]
    name = "example.cpp"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "safe_prime.cpp"
    number = 5
[[tests]]
    name = "Tonelli-Shanks_worstcase.cpp"
    number = 5

[params]
    T_MAX = 5_000
    P_MAX = 1_000_000_000
    K_MAX = 1_000_000_000
    
