title = 'Many A + B'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/329"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 2
[[tests]]
    name = "max_random.cpp"
    number = 2
[[tests]]
    name = "all_max.cpp"
    number = 1
[[tests]]
    name = "all_zero.cpp"
    number = 1

[params]
    T_MAX = 1_000_000
    A_AND_B_MAX = 1_000_000_000_000_000_000
