title = 'Point Set Range Sort Range Composite'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/818"


[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "small.cpp"
    number = 5

[[tests]]
    name = "random.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "many_0_query.cpp"
    number = 2

[[tests]]
    name = "many_1_query.cpp"
    number = 2

[[tests]]
    name = "many_2_query.cpp"
    number = 2

[[tests]]
    name = "many_3_query.cpp"
    number = 2

[[tests]]
    name = "sort_only_short.cpp"
    number = 2

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    MOD = 998_244_353
    N_MIN = 1
    N_MAX = 100_000
    P_MIN = 0
    P_MAX = 1_000_000_000
    Q_MIN = 1
    Q_MAX = 100_000
