title = 'Vertex Set Path Composite'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/190"
[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "random.cpp"
    number = 3

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "small.cpp"
    number = 5

[[tests]]
    name = "long-path-decomposition_killer.cpp"
    number = 1

[[tests]]
    name = "almost_line.cpp"
    number = 2
    
[[tests]]
    name = "line.cpp"
    number = 2
    
[[solutions]]
    name = "naive.cpp"
    expect = "RE"

[params]
    N_AND_Q_MAX = 200_000
    MOD = 998244353