title = 'Chromatic Number'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/628"

[[tests]]
    name = "example.in"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 10
[[tests]]
    name = "big.cpp"
    number = 10
[[tests]]
    name = "clique-cycle.cpp"
    number = 4

[params]
    MIN_N = 1
    MAX_N = 20
