title = 'Static Range Inversions Query'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/563"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small_n.cpp"
    number = 5
[[tests]]
    name = "small_a.cpp"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_MIN = 1
    N_MAX = 100_000
    Q_MIN = 1
    Q_MAX = 100_000
    A_MIN = 0
    A_MAX = 1000_000_000
