title = 'Unionfind'
timelimit = 5.0
forum = 'https://github.com/yosupo06/library-checker-problems/issues/33'

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 10
[[tests]]
    name = "path.cpp"
    number = 4

[params]
    N_MAX = 200_000
    Q_MAX = 200_000
