title = 'Rooted Tree Isomorphism Classification'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/796"

[[tests]]
    name = "example.in"
    number = 2

[[tests]]
    name = "max_isomorphic.cpp"
    number = 2

[[tests]]
    name = "max_line.cpp"
    number = 1

[[tests]]
    name = "max_random.cpp"
    number = 5

[[tests]]
    name = "max_star.cpp"
    number = 1

[[tests]]
    name = "small_random.cpp"
    number = 3

[[tests]]
    name = "sqrt.cpp"
    number = 1

[params]
    N_MIN = 1
    N_MAX = 500_000
