title = 'Kth term of Linearly Recurrent Sequence'
timelimit = 10.0
forum = 'https://github.com/yosupo06/library-checker-problems/issues/601'

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 10

[[tests]]
    name = "max_random.cpp"
    number = 3

[[tests]]
    name = "near_65536.cpp"
    number = 3

[[tests]]
    name = "random.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    expect = "RE"

[params]
  D_MAX = 100_000
  K_MAX = 1_000_000_000_000_000_000
  MOD = 998_244_353
