title = 'Range Kth Smallest'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/310"

[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "random.cpp"
    number = 5

[[tests]]
    name = "small.cpp"
    number = 10

[[tests]]
    name = "max_random.cpp"
    number = 5

[[tests]]
    name = "dense_small_a.cpp"
    number = 1

[[tests]]
    name = "dense_large_a.cpp"
    number = 1

[[tests]]
    name = "all_zero.cpp"
    number = 1

[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_MIN = 1
    N_MAX = 200_000
    Q_MIN = 1
    Q_MAX = 200_000
    A_MIN = 0
    A_MAX = 1000_000_000
