title = 'Exp of Set Power Series'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/974"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small_random.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "n_01.cpp"
    number = 2
[[tests]]
    name = "overflow.cpp"
    number = 1

[[solutions]]
    name = "naive.cpp"
    wrong = false
    allow_tle = true

[params]
    N_MAX = 20
    MOD = 998244353
