title = 'Area of Union of Rectangles'
timelimit = 5.0
forum = 'https://github.com/yosupo06/library-checker-problems/issues/787'

[[tests]]
    name = "example.cpp"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 5
[[tests]]
    name = "max_random.cpp"
    number = 5
[[tests]]
    name = "small.cpp"
    number = 5
[[tests]]
    name = "edge_bound.cpp"
    number = 5


[params]
    N_MAX = 500_000
    COORD_MAX = 1000_000_000
