timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/20"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "small.cpp"
    number = 2
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_AND_Q_MIN = 1
    N_AND_Q_MAX = 200_000
    A_ABS_MAX = 1_000_000_000
    B_ABS_MAX = 1_000_000_000_000_000_000
