title = 'Bitwise Xor Convolution'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/622"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "tiny.cpp"
    number = 3
[[tests]]
    name = "small.cpp"
    number = 3
[[tests]]
    name = "large.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3

[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_MAX = 20
    MOD = 998244353
