title = 'Range Chmin Chmax Add Range Sum'
timelimit = 10.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/243"
[[tests]]
    name = "example.in"
    number = 1

[[tests]]
    name = "small.cpp"
    number = 10
[[tests]]
    name = "medium.cpp"
    number = 3
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "random2.cpp"
    number = 3
[[tests]]
    name = "random3.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "small_absolute_values.cpp"
    number = 3

[[solutions]]
    name = "correct_with_assert.cpp"
[[solutions]]
    name = "naive.cpp"
    wrong = true

[params]
    N_AND_Q_MAX = 200_000
    A_ABS_MAX = 1_000_000_000_000
