title = 'K-Shortest Path (Directed)'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/508"

[[tests]]
	name = "example.in"
	number = 1

[[tests]]
	name = "random.cpp"
	number = 5

[[tests]]
	name = "max_random.cpp"
	number = 5

[[tests]]
	name = "inserting_pattern.cpp"
	number = 3

[[tests]]
	name = "thick_path.cpp"
	number = 2

[[tests]]
	name = "density.cpp"
	number = 10

[[tests]]
	name = "walk.cpp"
	number = 5

[[tests]]
	name = "hard_splitting.cpp"
	number = 1

[params]
	N_MIN = 2
	N_MAX = 1000
	M_MIN = 0
	M_MAX = 2000
	K_MIN = 1
	K_MAX = 10
	C_MIN = 1
	C_MAX = 1000_000_000
